version: "3.8"
services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    init: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./:/usr/src/financrr
    ports:
      - "127.0.0.1:3000:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine3.19
    init: true
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db/postgresql.conf:/etc/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} || exit 1'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  cache:
    image: redis:7.2.4-alpine3.19
    init: true
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redis-data:/data

volumes:
  postgres-data: ~
  redis-data: ~
