[package]
name = "backend"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Actix
actix-web = { version = "4.5.1", features = ["rustls-0_22", "secure-cookies"] }
actix-session = { version = "0.9.0", features = ["redis", "redis-rs-session"] }
actix-identity.workspace = true

# Validation
validator = { version = "0.16.1", features = ["derive"] }
actix-web-validator = "5.0.1"
iban = "0.1.7"

# Database / ORM
sea-orm.workspace = true
entity = { path = "../entity" }
migration = { path = "../migration" }
redis = "0.24.0"

# Serialization and deserialization
serde.workspace = true
serde_json = "1.0.113"

# Async runtime
tokio.workspace = true

# Generating openapi spec
utoipa = { version = "4.2.0", features = ["actix_extras", "openapi_extensions"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web", "debug-embed"] }
utoipauto = "0.1.8"

# Logging
log.workspace = true
simple_logger = "4.3.3"
time = "0.3.34" #Needed for giving timestamps to logs

# Utils
dotenvy = "0.15.7"
derive_more = { version = "1.0.0-beta.6", features = ["display", "error"] }
regex = {  version = "1.10.3", features = ["std", "perf", "unicode"] }
async-trait = "0.1.77"
chrono = "0.4.33"

# Future Utils
futures = "0.3.30"
futures-util = "0.3.30"
