version: "3.8"
services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    init: true
    restart: unless-stopped
    profiles:
      - all
    env_file:
      - .env
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./:/usr/src/financrr
      - ./logs:/home/financrr/logs
    ports:
      - "127.0.0.1:3000:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      search:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine3.19
    init: true
    restart: unless-stopped
    profiles:
      - dev
      - all
    environment:
      TZ: ${TIMEZONE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db/postgresql.conf:/etc/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} || exit 1'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  cache:
    image: redis:7.2.4-alpine3.19
    init: true
    restart: unless-stopped
    profiles:
      - dev
      - all
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redis-data:/data

  search:
    image: opensearchproject/opensearch:2.12.0 # Specifying the latest available image - modify if you want a specific version
    container_name: search
    init: true
    restart: unless-stopped
    profiles:
      - dev
      - all
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true # Disable JVM heap memory swapping
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${SEARCH_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
      DISABLE_SECURITY_PLUGIN: true
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    healthcheck:
      test: 'curl --fail localhost:9200/_cat/health >/dev/null || exit 1'
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - "127.0.0.1:9200:9200" # REST API
      - "127.0.0.1:9600:9600" # Performance Analyzer

volumes:
  postgres-data: ~
  redis-data: ~
  opensearch-data: ~
