services:
  hurl:
    build:
      dockerfile: docker/hurl/Dockerfile
    init: true
    volumes:
      - ./tests:/tests
    environment:
      HURL_admin_token: ${HURL_admin_token}

  rust:
    ports: []
    env_file:
      - .env.test

  db:
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./docker/db/postgresql.conf:/etc/postgresql.conf
    ports: []

  cache:
    volumes:
      - dragonflydata-test:/data
    ports: []


volumes:
  postgres-data-test: ~
  dragonflydata-test: ~
  logs: ~
