[package]
name = "entity"
version.workspace = true
edition.workspace = true

[dependencies]
# Actic
actix-session = { version = "0.9.0", features = ["redis", "redis-rs-session"] }

# Encryption
rand = "0.8.5"
rust-argon2 = "2.1.0"

# Error handling
anyhow = "1.0.79"

# Workspace
sea-orm.workspace = true
