name: (Backend Rust) Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

# Set default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Run unit tests
        run: cargo test --release --verbose --workspace

  build-and-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run e2e tests
        run: ./backend/bin/test-e2e.bash

