name: Docker Compose Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare for build
      run: bash bin/install.bash
    - name: Build the Docker compose images
      run: bash bin/build.bash
