name: Build Github Pages

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3 
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
